layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: loic-wendling-96408a74
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Google Scholar
    web_url: https://scholar.google.com/citations?user=k1RsW-gAAAAJ&hl=en&oi=ao
    image_url: https://cdn.worldvectorlogo.com/logos/google-scholar.svg

  - name: ResearchGate
    web_url: https://www.researchgate.net/profile/Loic_Wendling
    image_url: https://avatars0.githubusercontent.com/u/1073651?s=200&v=4
